AcceleSystem/Controllers/BrandController.cs
using Models;
using System.Web.Mvc;

namespace AcceleSystem.Controllers
{
    [SessionFilter]
    public class BrandController : Controller
    {
        // GET: Brand
        [SessionFilter]
        public ActionResult BrandList()
        {
            return View();
        }
        [SessionFilter]
        public ActionResult BrandEntry(BrandModel bmodel)
        {
            if(string.IsNullOrWhiteSpace(bmodel.Mode))
                bmodel.Mode = "New";
            return View(bmodel);
        }


    }
}

AcceleSystem/Controllers/KanagataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;

namespace AcceleSystem.Controllers
{
    [SessionFilter]
    public class KanagataController : Controller
    {
        // GET: Kanagata
        public ActionResult KanagataEntry(KanagataModel kgmodel)
        {
            if (string.IsNullOrWhiteSpace(kgmodel.Mode))
                kgmodel.Mode = "New";
            return View(kgmodel);
        }

        public ActionResult KanagataList()
        {
            return View();
        }
    }
}

AcceleSystem/Controllers/KeihiSetteiController.cs
using Models;
using System.Web.Mvc;

namespace AcceleSystem.Controllers
{
    [SessionFilter]
    public class KeihiSetteiController : Controller
    {
        // GET: KeihiSettei
        public ActionResult KeihiSetteiList()
        {
            return View();
        }

        public ActionResult KeihiSetteiEntry(KeihiSetteiModel Kmodel)
        {
            if (string.IsNullOrWhiteSpace(Kmodel.Mode))
                Kmodel.Mode = "New";
            return View(Kmodel);
        }
    }
}

AcceleSystem/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcceleSystem.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult BrandSearch()
        {
            return View();
        }

        public ActionResult BSearch()
        {
            return PartialView();
        }
    }
}

AcceleSystem/Controllers/UserController.cs
using Models;
using System.Web.Mvc;

namespace AcceleSystem.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        [SessionFilter]
        public ActionResult UserList()
        {
            return View();
        }
       
        public ActionResult UserLogIn()
        {
            return View();            
        }
        [SessionFilter]
        public ActionResult UserEntry(UserModel Umodel)
        {
            if (string.IsNullOrWhiteSpace(Umodel.Mode))
                Umodel.Mode = "New";
            return View(Umodel);
        }
    }
}

AcceleSystem/Views/Search/BSearch.cshtml
@{
    Layout = null;
}

<div class="card">
    <div class="card-body">
        <div class="row">
            <div id="divAdd" class="col-sm-2 col-md-3">
                <button id="btnAdd" onclick="btnAddClick()" class="btn col-xl-10 text-center" tabindex="38" style="background-color:#1a8cff; color:azure;">
                    ブランド追加
                </button>
            </div>

            <div class="col-sm-8 col-md-8 col-lg-8">
                <i class="fa fa-search" style="padding-left:15px;"></i>
                <input type="text" id="myInput" placeholder="ブランド名入力" class="border border-white" style="width:80%;padding-bottom:10px">
                <table id="tblBrand" class="tb1 col-sm-12" style="padding-left:0px;width:100%">
                    <thead>
                        <tr>
                            <th>
                                <table>
                                    <tr class="col-md-12">
                                        <th style="width:20%">ブランドコード</th>
                                        <th style="width:60%">ブランド名</th>
                                        <th style="width:20%"></th>
                                    </tr>
                                </table>
                            </th>

                        </tr>
                    </thead>

                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function BrandLoad() {
        $("#divAdd").hide();
    }
</script>

AcceleSystem/Views/Search/BrandSearch.cshtml
@{
    Layout = null;
}

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-8 col-md-8 col-lg-8">
                <i class="fa fa-search" style="padding-left:15px;"></i>
                <input type="text" id="myInput" placeholder="ブランド名入力" class="border border-white" style="width:80%;padding-bottom:10px">
                <table id="tblBrand" class="tb1 col-sm-12" style="padding-left:0px;width:100%">
                    <thead>
                        <tr>
                            <th>
                                <table>
                                    <tr class="col-md-12">
                                        <th style="width:20%">ブランドコード</th>
                                        <th style="width:60%">ブランド名</th>
                                        <th style="width:20%"></th>
                                    </tr>
                                </table>
                            </th>

                        </tr>
                    </thead>

                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function BrandLoad() {
        $("#formtitle").text("ブランド検索");
        GetBrand();
        $("#myInput").focus();
    }
</script>

AcceleSystem/Views/Search/SearchBase.cshtml
<div id="divSearch" data-iziModal-title="Order Select" data-iziModal-icon="icon-home">
    <input id="Htype" type="hidden" value="0"/>
    <div id="divSearch1">

    </div>
</div>
<div id="divSearch2" data-iziModal-title="Order Select" data-iziModal-icon="icon-home">
    <div id="divSearch3">

    </div>
</div>

<script type="text/javascript">
    var CD;
    var Name;
    var CD1;
    var typeID;
    function LoadSearchForm(typeID, CD, Name, CD1) {
        $('#Htype').val(typeID);

        this.CD = CD;
        this.Name = Name;
        this.CD1 = CD1;
        this.typeID = typeID;

        if (typeID == 9) {
            $("#divSearch1 #divMainList").hide();
            $("#divSearch3").empty();
        }
        else {
            $("#divSearch1").empty();
        }

        switch (typeID) {
            case 1:
                $(".iziModal-header-title").text("ブランド検索");
                $("#divSearch1").load('@Url.Action("BrandList","Brand")', function () {
                    SearchSetting(typeID);
                });
                break;
            case 9:
                $(".iziModal-header-title").text("ブランド検索");
                $("#divSearch3").load('@Url.Action("BrandList","Brand")', function () {
                    SearchSetting(typeID);
                });
                break;
            case 2:
                $(".iziModal-header-title").text("ユーザー検索");
                $("#divSearch1").load('@Url.Action("UserList","User")', function () {
                    SearchSetting(typeID);
                });
                break;
            case 3:
                $(".iziModal-header-title").text("品番検索");
                $("#divSearch1").load('@Url.Action("TourokuHinban_Search", "TourokuProject")', function () {
                    SearchSetting(typeID);
                    if ($("#divMain #proCD").val()) {
                        $("#divMainList #HLHinbanName").focus();
                    }
                    else {
                        $("#divMainList #proName").focus();
                    }
                });
                break;
            case 4:
            case 7:
                $(".iziModal-header-title").text("金型検索");
                $("#divSearch1").load('@Url.Action("KanagataList", "Kanagata")', function () {
                    SearchSetting(typeID);
                });
                break;
            case 5:
                $(".iziModal-header-title").text("経費検索");
                $("#divSearch1").load('@Url.Action("Touroku_KeihiList", "Touroku_Keihi")', function () {
                    SearchSetting(typeID);
                });
                break;
            case 6:
                $(".iziModal-header-title").text("プロジェクト検索");
                $("#divSearch1").load('@Url.Action("TourokuProject_List", "TourokuProject")', function () {
                    SearchSetting(typeID);
                });
                break;
             case 8:
                $(".iziModal-header-title").text("経費設定検索");
                $("#divSearch1").load('@Url.Action("KeihiSetteiList", "KeihiSettei")', function () {
                    SearchSetting(typeID);
                });
                break;
        }
    }

    function SearchSetting(type) {
        switch (type) {
            case 1:
            case 9:
                $("#BrandType").val("2");
                GetBrand();
                $("#myInput").focus();
                $("#divAddBrand").hide();
                break;
            case 2:
                $("#UserType").val("2");
                GetUser();
                $("#UserInput").focus();
                $("#divAddUser").hide();
                break;
            case 3:
                HinbanSearch_Load();
                $("#HinbanType").val("2");
                $("#divSearch1 #btnAdd").hide();
                $("#divSearch1 #btnnext").hide();
                $("#divSearch1 #btnHibanSearch").hide();
                $("#divSearch1 #btnProjectSearch").hide();
                $("#divSearch1 #btnBrandSearch").hide();
                break;
            case 4:
            case 7:
                $("#KanagataType").val("2");
                GetCasting();
                $("#KanagataInput").focus();
                $('#divAddKanagata').hide();
                break;
            case 5:
                $("#KeihiType").val("2");
                KeihiList_Load();
                break;
            case 6:
                $("#ProjectType").val("2");
                ProjectList_Load();
                $("#divSearch1 #divbtn").hide();
                //$("#divSearch1 #btnnext").hide();
                $("#divSearch1 #btnCSV").hide();
                //$("#divSearch1 #btnPSearch").hide();
                $("#divSearch1 #btnPUser").hide();
                break;
            case 8:
                $("#KeihiSettieType").val("2");
                GetKeihi();
                $("#myInput").focus();
                $("#divAddKeihiSettie").hide();
                break;
        }

        if (typeID == 9) {
            $("#divSearch2").iziModal('open');
        }
        else {
            $("#divSearch").iziModal('open');
        }
        //$("#divSearch").iziModal('open');
    }

    function ReturnSelected(cd, name, cd1) {
        if (($("#Htype").val() == 9)){
            $("#divSearch1 #divMainList").show();
            $("#divSearch3").empty();

            $("#divMainList #BrandCD").val(cd);
            $("#divMainList #BrandName").val(name);
            $(".iziModal-header-title").text("プロジェクト検索");
            $('#Htype').val(6);
            
            CD = $("#proCD")
            Name = $("#proName")
        }
        else {
            typeID = $('#Htype').val();
            $("#divSearch1").empty();

            $(CD).val(cd);
            $(Name).val(name);
            $(CD1).val(cd1);
            $("#divSearch").iziModal('close');

            //fire keydown of BrandName
            var e = jQuery.Event("keydown");
            e.which = 13; // # Some key code value

            if ($(Name).is('input')) {
                $(Name).trigger(e);
            }
            else if ($(CD).is('input')) {
                $(CD).trigger(e);
            }
            else {
                $(CD1).trigger(e);
            }

            if ($("#formtitle").text() == "品番検索" && typeID == 6) { Check(); } //BindProjectData as ProjectCD(From ProjectSearch) entered in HinbanList
            else if ($("#formtitle").text() == "品番登録" && (!$(CD1).length)) { ShowProjectData(); }//Bind ProjectData as ProjectCD (From ProjectSearch) entered in HinbanEntry
            else if ($("#formtitle").text() == "品番登録" && ($(CD1).length)) { GetSearchData(); } //Bind HinbanData as HinbanCD and ProjectCD (From HinbanSearch) entered in HinbanEntry

            //errortask 200->208 tabcase_2021/05/12 by sypk
            if ($("#divMainList").is(":visible")) {
                do {
                    CD = $('#divMainList [tabIndex=' + (+$(CD).attr("tabIndex") + 1) + ']');
                    if (!$(CD).length) {
                        ctrl = $('#divMainList [tabIndex=1]');
                        break;
                    }
                } while ($(CD).is('[disabled=disabled]'));
                $(CD).select();
                $(CD).focus();
            }
            else if ($("#divMain").is(":visible")) {
                do {
                    CD = $('#divMain [tabIndex=' + (+$(CD).attr("tabIndex") + 1) + ']');
                    if (!$(CD).length) {
                        ctrl = $('#divMain [tabIndex=1]');
                        break;
                    }
                } while ($(CD).is('[disabled=disabled]'));
                $(CD).select();
                $(CD).focus();
            }
        }      
    }


</script>